#!/usr/bin/groovy
def k8s_token = '<unknown>'

node ('master') {
    k8s_token = readFile '/var/run/secrets/kubernetes.io/serviceaccount/token'
}

node('maven') {
    def k8s_namespace = readFile '/var/run/secrets/kubernetes.io/serviceaccount/namespace'

    stage 'Checkout'
    checkout scm

    stage 'Build'
    sh 'mvn clean compile'

    stage 'Package'
    sh 'mvn package'

    stage 'Archive artifact'
    sh 'mkdir -p ../artifacts/deployments/ && cp target/*.war ../artifacts/deployments/'
    archive 'target/*.war'

    stage 'Create Image'
    sh "oc login https://kubernetes.default/ --token=${k8s_token} --certificate-authority=/run/secrets/kubernetes.io/serviceaccount/ca.crt"

    // Prepare the deployments so you can see pipeline in console overview when running for the first time
    sh 'oc process -f .openshift-pipeline/empty-deployment-template.yaml -v "APP_NAME=kitchensink-html5-app" | oc apply -f -'

    sh 'oc process -f https://github.com/tnozicka/openshift-templates/raw/master/binary-build-template.yaml \
       -v "APP_NAME=kitchensink-html5-app,BUILDER_IMAGE=registry.access.redhat.com/jboss-eap-7/eap70-openshift,OUTPUT_IMAGESTREAM_TAG=kitchensink-html5-app:latest"| oc create -f -'
    sh 'oc start-build kitchensink-html5-app --from-dir=../artifacts/ --wait'

    stage 'Deploy'
    sh "oc process -f .openshift-pipeline/deployment-template.yaml -v 'APP_NAME=kitchensink-html5-app,IMAGE_STREAM_NAMESPACE=${k8s_namespace},IMAGE_STREAM_TAG=kitchensink-html5-app:latest' | oc apply -f -"
    sh 'oc annotate is kitchensink-html5-app misc_$(date +%s)=foo || true'  // Hack for 0-2 minute pause caused by https://github.com/openshift/origin/issues/9018

}
